# netlify.toml

[build]
  # Build command: install Quarto CLI and then render the site
  command = """
  bash -c '
    set -euo pipefail
    QUARTO_VERSION="1.10.4"
    TGZ="quarto-${QUARTO_VERSION}-linux-amd64.tar.gz"
    URL="https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/${TGZ}"
    echo "Installing Quarto ${QUARTO_VERSION}..."
    curl -fsSL -o "${TGZ}" "${URL}"
    tar -xzf "${TGZ}"
    mkdir -p "$HOME/quarto"
    mv "quarto-${QUARTO_VERSION}"/* "$HOME/quarto/"
    export PATH="$HOME/quarto/bin:$PATH"
    quarto --version
    quarto render
  '
  """
  
  # Folder where the rendered site will be published
  publish = "_site"  # change this if your Quarto site outputs elsewhere
