# netlify.toml

[build]
  publish = "docs"
  command = """
  # Fetch the latest Quarto release tag from GitHub
  LATEST=$(curl -s https://api.github.com/repos/quarto-dev/quarto-cli/releases/latest | grep -Po '\"tag_name\": \"\\K[^\"]+')
  QUARTO_VERSION=${LATEST#v}   # Remove leading 'v' if present

  # Download the tarball for the latest version
  TGZ="quarto-${QUARTO_VERSION}-linux-amd64.tar.gz"
  curl -L -o "$TGZ" "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/${TGZ}"

  # Extract Quarto locally
  tar -xzf "$TGZ"
  mkdir -p "$HOME/quarto"
  mv "quarto-${QUARTO_VERSION}"/* "$HOME/quarto/"

  # Add Quarto to PATH
  export PATH="$HOME/quarto/bin:$PATH"

  # Confirm installation and render site
  quarto --version
  quarto render
  """
