# netlify.toml
[build]
  command = """
  bash -c '
    set -euo pipefail
    echo "Fetching latest Quarto release version..."
    QUARTO_VERSION=$(curl -s https://api.github.com/repos/quarto-dev/quarto-cli/releases/latest | grep -Po '"tag_name": "\\K[^"]+')
    QUARTO_VERSION=${QUARTO_VERSION#v}  # strip leading v if present
    TGZ="quarto-${QUARTO_VERSION}-linux-amd64.tar.gz"
    URL="https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/${TGZ}"
    echo "Installing Quarto ${QUARTO_VERSION} from ${URL}..."
    curl -fsSL -o "${TGZ}" "${URL}"
    tar -xzf "${TGZ}"
    mkdir -p "$HOME/quarto"
    mv "quarto-${QUARTO_VERSION}"/* "$HOME/quarto/"
    export PATH="$HOME/quarto/bin:$PATH"
    quarto --version
    quarto render
  '
  """
  publish = "_site"
